### PR TITLE
Fixed stylings around invalid select fields

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**
Addresses: https://github.com/blackbaud/skyux2/issues/2132

### CODE REVIEW

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ToddRoberts this will fix the Sky Select Field component

**Review by Blackbaud-AlexKingman — COMMENTED** [review]
@Blackbaud-TrevorBurch These changes are just for the visual demo. I was expecting to see some styles for the `.ng-invalid` state. Am I missing something?

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-AlexKingman I think I accidentally committed the wrong file. One second

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-AlexKingman Fixed. Sorry about that. I think I clicked the wrong `scss` file when staging things.

**Review by Blackbaud-AlexKingman — DISMISSED** [review]
Easy fix. Looks good. Let's make a future work item to take care of some visual tests around invalid states.

**Review by Blackbaud-SteveBrush — CHANGES_REQUESTED** [review]
Let's get a visual test to demonstrate this working.

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
